/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_maehem_copper_pi_NativeControllerImpl */

#ifndef _Included_com_maehem_copper_pi_NativeControllerImpl
#define _Included_com_maehem_copper_pi_NativeControllerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    initialise
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    terminate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_terminate
  (JNIEnv *, jobject);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    setMode
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_setMode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    getMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_getMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    setPullUpDown
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_setPullUpDown
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    read
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_read
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    write
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_write
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    pwm
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_pwm
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    pwmGetDutyCycle
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_pwmGetDutyCycle
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    pwmSetFrequency
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_pwmSetFrequency
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    pwmGetFrequency
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_pwmGetFrequency
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    pwmSetRange
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_pwmSetRange
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    pwmGetRange
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_pwmGetRange
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    pwmGetRealRange
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_pwmGetRealRange
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    servo
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_servo
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    servoGetPulsewidth
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_servoGetPulsewidth
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    getHardwareRevision
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_getHardwareRevision
  (JNIEnv *, jobject);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    time
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_time
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    sleep
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_sleep
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    delay
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_delay
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    tick
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_tick
  (JNIEnv *, jobject);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    spiOpen
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_spiOpen
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    spiClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_spiClose
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    spiRead
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_spiRead
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    spiWrite
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_spiWrite
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    spiXfer
 * Signature: (I[B[BI)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_spiXfer
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    i2cOpen
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_i2cOpen
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    i2cClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_i2cClose
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    i2cWriteQuick
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_i2cWriteQuick
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    i2cWriteByte
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_i2cWriteByte
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    i2cReadByte
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_i2cReadByte
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    i2cWriteByteData
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_i2cWriteByteData
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    i2cWriteWordData
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_i2cWriteWordData
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    i2cReadByteData
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_i2cReadByteData
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    i2cReadWordData
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_i2cReadWordData
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    i2cProcessCall
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_i2cProcessCall
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    i2cWriteBlockData
 * Signature: (II[BI)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_i2cWriteBlockData
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    i2cReadBlockData
 * Signature: (II[B)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_i2cReadBlockData
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    i2cBlockProcessCall
 * Signature: (II[BI)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_i2cBlockProcessCall
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    i2cReadI2CBlockData
 * Signature: (II[BI)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_i2cReadI2CBlockData
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    i2cWriteI2CBlockData
 * Signature: (II[BI)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_i2cWriteI2CBlockData
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    i2cReadDevice
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_i2cReadDevice
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    i2cWriteDevice
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_i2cWriteDevice
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    i2cSwitchCombined
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_i2cSwitchCombined
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    i2cSegments
 * Signature: (I[Ljava/lang/Object;I)I
 */
//JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_i2cSegments
//  (JNIEnv *, jobject, jint, jobjectArray, jint);

/*
 * Class:     com_maehem_copper_pi_NativeControllerImpl
 * Method:    i2cZip
 * Signature: (I[BI[BI)I
 */
//JNIEXPORT jint JNICALL Java_com_maehem_copper_pi_NativeControllerImpl_i2cZip
//  (JNIEnv *, jobject, jint, jbyteArray, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
