/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class copper_InterfaceImpl */

#ifndef _Included_copper_InterfaceImpl
#define _Included_copper_InterfaceImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     copper_InterfaceImpl
 * Method:    wiringPiSetup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_copper_InterfaceImpl_wiringPiSetup
  (JNIEnv *, jobject);

/*
 * Class:     copper_InterfaceImpl
 * Method:    wiringPiSetupGpio
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_copper_InterfaceImpl_wiringPiSetupGpio
  (JNIEnv *, jobject);

/*
 * Class:     copper_InterfaceImpl
 * Method:    wiringPiSetupPhys
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_copper_InterfaceImpl_wiringPiSetupPhys
  (JNIEnv *, jobject);

/*
 * Class:     copper_InterfaceImpl
 * Method:    wiringPiSetupSys
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_copper_InterfaceImpl_wiringPiSetupSys
  (JNIEnv *, jobject);

/*
 * Class:     copper_InterfaceImpl
 * Method:    pinMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_copper_InterfaceImpl_pinMode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     copper_InterfaceImpl
 * Method:    pullUpDnControl
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_copper_InterfaceImpl_pullUpDnControl
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     copper_InterfaceImpl
 * Method:    digitalWrite
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_copper_InterfaceImpl_digitalWrite
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     copper_InterfaceImpl
 * Method:    pwmWrite
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_copper_InterfaceImpl_pwmWrite
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     copper_InterfaceImpl
 * Method:    digitalRead
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_copper_InterfaceImpl_digitalRead
  (JNIEnv *, jobject, jint);

/*
 * Class:     copper_InterfaceImpl
 * Method:    analogRead
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_copper_InterfaceImpl_analogRead
  (JNIEnv *, jobject, jint);

/*
 * Class:     copper_InterfaceImpl
 * Method:    analogWrite
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_copper_InterfaceImpl_analogWrite
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     copper_InterfaceImpl
 * Method:    millis
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_copper_InterfaceImpl_millis
  (JNIEnv *, jobject);

/*
 * Class:     copper_InterfaceImpl
 * Method:    micros
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_copper_InterfaceImpl_micros
  (JNIEnv *, jobject);

/*
 * Class:     copper_InterfaceImpl
 * Method:    delay
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_copper_InterfaceImpl_delay
  (JNIEnv *, jobject, jint);

/*
 * Class:     copper_InterfaceImpl
 * Method:    delayMicroseconds
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_copper_InterfaceImpl_delayMicroseconds
  (JNIEnv *, jobject, jint);

/*
 * Class:     copper_InterfaceImpl
 * Method:    wiringPiSPISetup
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_copper_InterfaceImpl_wiringPiSPISetup
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     copper_InterfaceImpl
 * Method:    wiringPiSPIDataRW
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_copper_InterfaceImpl_wiringPiSPIDataRW
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     copper_InterfaceImpl
 * Method:    wiringPiI2CSetup
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_copper_InterfaceImpl_wiringPiI2CSetup
  (JNIEnv *, jobject, jint);

/*
 * Class:     copper_InterfaceImpl
 * Method:    wiringPiI2CRead
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_copper_InterfaceImpl_wiringPiI2CRead
  (JNIEnv *, jobject, jint);

/*
 * Class:     copper_InterfaceImpl
 * Method:    wiringPiI2CWrite
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_copper_InterfaceImpl_wiringPiI2CWrite__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     copper_InterfaceImpl
 * Method:    wiringPiI2CWrite
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_copper_InterfaceImpl_wiringPiI2CWrite__I_3BI
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     copper_InterfaceImpl
 * Method:    wiringPiI2CWriteReg8
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_copper_InterfaceImpl_wiringPiI2CWriteReg8
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     copper_InterfaceImpl
 * Method:    wiringPiI2CWriteReg16
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_copper_InterfaceImpl_wiringPiI2CWriteReg16
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     copper_InterfaceImpl
 * Method:    wiringPiI2CReadReg8
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_copper_InterfaceImpl_wiringPiI2CReadReg8
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     copper_InterfaceImpl
 * Method:    wiringPiI2CReadReg16
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_copper_InterfaceImpl_wiringPiI2CReadReg16
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
